#!/usr/bin/env bash
# mg_fetch.sh — download MolluscaGenes artifacts from Zenodo, verify checksums,
# extract tarballs, and emit a populated config.sh ready to be sourced.
#
# Usage:
#   mg_fetch.sh <storage_dir> [--zenodo-record <id>] [--dry-run] [--no-extract]
#
# By default, the Zenodo record ID is read from metadata/zenodo_record.txt (if
# present) or you can pass --zenodo-record. The record ID is the numeric id at
# the end of the Zenodo record URL.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${here}/.." && pwd)"

usage() {
    cat >&2 <<EOF
Usage: $(basename "$0") <storage_dir> [options]

Required:
  <storage_dir>           where to download (will be created)

Options:
  --zenodo-record ID      override the Zenodo record id
  --dry-run               print what would be downloaded, don't download
  --no-extract            skip extracting BLAST / HMM tarballs after download
  --no-config             don't write a config.sh
  -h | --help             this help

After download + verify, writes <repo>/config.sh with paths populated to point
at <storage_dir>. Source it before using any wrapper.
EOF
}

storage=""
zenodo_id=""
dry_run="no"
extract="yes"
write_config="yes"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --zenodo-record) zenodo_id="$2"; shift 2 ;;
        --dry-run) dry_run="yes"; shift ;;
        --no-extract) extract="no"; shift ;;
        --no-config) write_config="no"; shift ;;
        -h|--help) usage; exit 0 ;;
        --) shift; break ;;
        -*) echo "unknown arg: $1" >&2; usage; exit 2 ;;
        *) [[ -z "$storage" ]] && storage="$1" || { echo "extra arg: $1" >&2; exit 2; }; shift ;;
    esac
done

[[ -z "$storage" ]] && { usage; exit 2; }

if [[ -z "$zenodo_id" ]]; then
    [[ -f "${repo_root}/metadata/zenodo_record.txt" ]] && \
        zenodo_id=$(< "${repo_root}/metadata/zenodo_record.txt")
fi
[[ -z "$zenodo_id" ]] && { echo "error: no Zenodo record id (set metadata/zenodo_record.txt or use --zenodo-record)" >&2; exit 1; }

command -v curl >/dev/null 2>&1     || { echo "error: curl required" >&2; exit 1; }
command -v sha256sum >/dev/null 2>&1 || { echo "error: sha256sum required" >&2; exit 1; }
command -v jq >/dev/null 2>&1       || { echo "error: jq required" >&2; exit 1; }

manifest="${repo_root}/metadata/zenodo_manifest.tsv"
[[ -f "$manifest" ]] || { echo "error: manifest not found: $manifest" >&2; exit 1; }

mkdir -p "$storage"
echo "fetching Zenodo record $zenodo_id metadata..."
api_url="https://zenodo.org/api/records/${zenodo_id}"
record_json=$(curl -fsSL "$api_url") || { echo "failed to GET $api_url" >&2; exit 1; }

# Build a fname -> download_url map
declare -A url_for
while IFS=$'\t' read -r fn url; do
    url_for["$fn"]="$url"
done < <(echo "$record_json" | jq -r '.files[] | "\(.key)\t\(.links.self)"')

if [[ "$dry_run" == "yes" ]]; then
    echo "DRY RUN: would download:"
    while IFS=$'\t' read -r fname size sha desc; do
        [[ "$fname" == "filename" || -z "$fname" ]] && continue
        printf '  %s\t%s\t%s\n' "$fname" "$size" "${url_for[$fname]:-MISSING-IN-ZENODO}"
    done < "$manifest"
    exit 0
fi

# Download each file listed in the manifest
while IFS=$'\t' read -r fname size sha desc; do
    [[ "$fname" == "filename" || -z "$fname" ]] && continue
    out="${storage}/${fname}"
    url="${url_for[$fname]:-}"
    if [[ -z "$url" ]]; then
        echo "  SKIP  $fname (not in Zenodo record)"; continue
    fi
    if [[ -f "$out" ]]; then
        actual_sha=$(sha256sum "$out" | awk '{print $1}')
        if [[ "$actual_sha" == "$sha" ]]; then
            echo "  OK    $fname (already present, sha matches)"; continue
        else
            echo "  RE    $fname (sha mismatch, re-downloading)"
            rm -f "$out"
        fi
    fi
    echo "  GET   $fname ($size bytes)"
    curl -fSL --progress-bar "$url" -o "$out"
done < "$manifest"

echo
echo "verifying checksums..."
"${here}/verify_download.sh" "$storage"

if [[ "$extract" == "yes" ]]; then
    echo
    echo "extracting tarballs..."
    for tgz in "${storage}"/*.tar.gz; do
        [[ -e "$tgz" ]] || continue
        echo "  tar -xzf $(basename "$tgz")"
        tar -xzf "$tgz" -C "$storage"
    done
fi

if [[ "$write_config" == "yes" ]]; then
    config="${repo_root}/config.sh"
    abs_storage="$(cd "$storage" && pwd)"
    cat > "$config" <<EOF
# Auto-generated by mg_fetch.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
export MG_BLAST_DIR="${abs_storage}"
export MG_BLAST_AA="\${MG_BLAST_DIR}/mollusca_aa"
export MG_BLAST_MRNA="\${MG_BLAST_DIR}/mollusca_mrna"
export MG_DIAMOND_AA="\${MG_BLAST_DIR}/mollusca_aa.dmnd"
export MG_HMM="\${MG_BLAST_DIR}/mollusca_revised_hmms.hmm"
export MG_METADATA="\$(cd "\$(dirname "\${BASH_SOURCE[0]:-\$0}")" && pwd)/metadata"
export MG_THREADS=10
EOF
    echo "wrote $config"
    echo
    echo "next: source ${config#${PWD}/}"
fi

echo "fetch complete."
